version: "3"

services:


  ### nginx
  #nginx:
  #  image: nginx
  #  depends_on:
  #   - s3-storage
  #  volumes:
  #    - ../nginx:/etc/nginx/:ro
  #  ports:
  #    - 8081:80
  #  networks:
  #    - storage
  #    - default

  ###
  
  ### Schul-Cloud Server
  ###
  server-mongodb:
    image: mongo:4.0
    ports:
      - "27017:27017"
    volumes:
      - data-server-mongodb:/data/db
    restart: unless-stopped

  server:
    #image: schulcloud/schulcloud-server:latest
    build:
      context: ../schulcloud-server
      dockerfile: Dockerfile
    volumes:
      - ../schulcloud-server:/schulcloud-server
    depends_on:
      - server-mongodb
    environment:
      # ENV
      - NODE_ENV=production
      - HOST=http://localhost:3030
      - SC_TITLE=HPI Schulcloud
      - SC_SHORT_TITLE=Schulcloud
      # SMTP
      # - SMTP=
      # - SMTP_SENDER=
      # Storage
      - AWS_ENDPOINT_URL=https://dev-storage.schul-cloud.org:9001
      #- AWS_ENDPOINT_URL=http://localhost:9000
      ## keys for local s3 storage
      # - AWS_ACCESS_KEY=
      # - AWS_SECRET_ACCESS_KEY=
      # URIs and Port
      - MONGO_URI=mongodb://server-mongodb:27017/schulcloud
      - DB_URL=mongodb://server-mongodb:27017/schulcloud
      - CALENDAR_URI=http://calendar:3000
      - CONTENT_URI=https://consent.schul-cloud.org
      - NOTIFICATION_URI=http://notification:3030
      - PORT=3030
      # RocketChat
      - ROCKET_CHAT_URI=https://chat.schulcloud.local
#      - ROCKET_CHAT_ADMIN_TOKEN=
    #  - ROCKET_CHAT_ADMIN_TOKEN= 
    #  - ROCKET_CHAT_ADMIN_ID=
      # AUTH Secret
      # - AUTHENTICATION=
      - IGNORE_DISCOVERABILITY=true
      # file preview service
      - ENABLE_THUMBNAIL_GENERATION=true
      - FILE_PREVIEW_SERVICE_URI=http://filepreview:3000/filepreview
      - FILE_PREVIEW_CALLBACK_URI=http://server:3030/fileStorage/thumbnail/
      # FEATURE TOGGLES
      - LERNSTORE_MODE=LEGACY
    ports:
      - "3030:3030"
      - "5959:5959"
    networks:
      - storage
      - default
    restart: unless-stopped
    command: npm run debug:container
  ###

  ### Schul-Cloud Client
  ###
  client:
    #image: schulcloud/schulcloud-client:develop
    build:
      context: ../schulcloud-client
      dockerfile: Dockerfile
    volumes:
      - ../schulcloud-client:/home/node/app
      - /home/node/app/build
    depends_on:
      - server
    environment:
      # ENV
      - NODE_ENV=development
      - DOCKER=true
      - CALENDAR_SERVICE_ENABLED=true
      #- TZ=Europe/Berlin
      # Theme and Titles
      - SC_TITLE=HPI Schulcloud
      - SC_SHORT_TITLE=Schulcloud
      - SC_PRODUCTNAME=Hauptschule
      - SC_FEDERALSTATE=mainstate
      # Google
      #- GOOGLE_ANALYTICS_TRACKING_ID="UA-155982548-1"
      # URIs
      - HOST=http://localhost:3100
      - BACKEND_URL=http://server:3030
      - PUBLIC_BACKEND_URL=https://localhost:3030
      - LIBRE_OFFICE_CLIENT_URL=http://localhost:9980
      - ROCKET_CHAT_URI=https://chat.schulcloud.local
      # FEATURE TOGGLES
      - FEATURE_TEAMS_ENABLED=true
      - LERNSTORE_MODE=LEGACY
      - ROCKETCHAT_SERVICE_ENABLED=true
      - EDTR_SOURCE=https://cdn.jsdelivr.net/gh/schul-cloud/edtrio@e9d3bb9d66092bafa07846269c8fc6f9d5fb0559/dist/index.js
    ports:
      - "3100:3100"
      - "9310:9310" #debug port
      - "7000:7000"
    restart: unless-stopped
    command: bash -c "gulp & gulp watch-reload"
  ###


  ### Schul-Cloud Calendar
  ###
  calendar-postgres:
    image: postgres:9.5
    ports:
      - "5432:5432"
    volumes:
      - 'data-calendar-postgres:/var/lib/postgresql/data'
      - 'postgres-init:/docker-entrypoint-initdb.d'
    environment:
      - POSTGRES_DB=schulcloud_calendar
      - POSTGRES_USER=node
      - POSTGRES_PASSWORD=genericpassword
    restart: unless-stopped


  calendar:
    image: schulcloud/schulcloud-calendar
    build:
      context: ../schulcloud-calendar
      dockerfile: Dockerfile.develop
    ports:
      - "3000"
    depends_on:
      - calendar-postgres
    volumes:
      - 'postgres-init:/docker-entrypoint-initdb.d'
    environment:
      # ENV
      - NODE_ENV=production
      # DB Credentials
      - DB_PASSWORD=genericpassword
      - DB_HOST=calendar-postgres
      - DB_USERNAME=node
      - DB_DATABASE=schulcloud_calendar
      # Paths
      - SCHULCLOUD_BASE_PATH=http://server:3030
      - NOTIFICATION_SERVICE_BASE_PATH=http://notification:3040
      - SCHULCLOUD_ALL_USERS_FOR_UUID=http://server:3030/resolve/users/
      - SCHULCLOUD_ALL_SCOPES_FOR_TOKEN=http://server:3030/resolve/scopes/
      - NOTIFICATION_SERVICE_NEW_NOTIFICATION=http://notification:3040/messages
    restart: unless-stopped
    command: npm start

  ###

  ### Schul-Cloud Notifications
  ###

  ###

  
  ### Schul-Cloud Content
  ###
  
  ###


  
  
  ### Filepreview
  ###
  redis:
    image: redis:latest
    command: ["redis-server", "--appendonly", "yes"]
    hostname: redis
    restart: unless-stopped

  filepreview:
    image: schulcloud/filepreview:latest
    build:
      context: ../filepreview
      dockerfile: Dockerfile
    volumes:
      - ../filepreview:/home/node/app
    environment:
      USERNAME: filepreview
      PASSWORD: strongPassword
      REDIS_HOST: redis
    ports:
      - "3000"
    networks:
      - default
      - storage
    depends_on:
      - redis
    restart: unless-stopped

  ###
networks:
  storage:
    ipam:
      driver: default
      config:
        - subnet: "172.16.13.0/24"



volumes:
  data-server-mongodb:
  data-calendar-postgres:
  data-s3-storage:
  db-data:
  postgres-init:
