version: "3"

services:



  ### kong api gateway
  kong-database:
    restart: on-failure
    image: cassandra:3
    container_name: kong-database
    ports:
      - "9042:9042"
    volumes:
      - "data-kong-cassandra:/var/lib/cassandra"

  kong:
    restart: on-failure
    image: kong
    container_name: kong
    depends_on:
      - kong-database
      - kong-migration
    ports:
      - "80:8000"
      - "443:8443"
      - "8001:8001"
      - "7946:7946"
      - "7946:7946/udp"
    environment:
      - KONG_DATABASE=cassandra
      - KONG_ADMIN_LISTEN=0.0.0.0:8001, 0.0.0.0:8444 ssl
      - KONG_CASSANDRA_CONTACT_POINTS=kong-database
      - DB_UPDATE_PROPAGATION=5

  kong-migration:
    restart: on-failure
    image: kong:latest
    container_name: kong-migration
    depends_on:
     - kong-database
    environment:
     - KONG_DATABASE=cassandra
     - KONG_CASSANDRA_CONTACT_POINTS=kong-database
     - DB_UPDATE_PROPAGATION=5
    command: kong migrations bootstrap