version: "3"

services:
  server:
    # env_file:
    #   - ../envs/end-to-end-tests.env
    command: npm run start

  client:
    # env_file:
    #   - ../envs/end-to-end-tests.env
    environment:
      - DOCKER=true
    command: npm run start

  #nuxtclient:
    # env_file:
    #   - ../envs/end-to-end-tests.env

  notification-service:
    #env_file:
    #  - ../envs/end-to-end-tests.env

  # Selenium Server
  selenium-hub:
    image: selenium/hub:3.141.59-titanium
    container_name: selenium-hub
    ports:
      - "4444:4444"
  chrome:
    image: selenium/node-chrome:3.141.59-titanium
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
#   firefox:
#     image: selenium/node-firefox:3.141.59-titanium
#     volumes:
#       - /dev/shm:/dev/shm
#     depends_on:
#       - selenium-hub
#     environment:
#       - HUB_HOST=selenium-hub
#       - HUB_PORT=4444