version: "3"

services:

  server:
    depends_on:
      - notification-service
    environment:
      - NOTIFICATION_URI=http://notification-service:3031
      - FORCE_SEND_EMAIL=true

  ###
  ### Schul-Cloud Notifications
  ###
  notification-service:
    image: schulcloud/node-notification-service:${NOTIFICATION_SERVICE_PATH_DOCKER_TAG:-latest}
    build:
      context: ${NOTIFICATION_SERVICE_PATH:-/dev/null}
      dockerfile: Dockerfile
    container_name: notification-service
    ports:
      - 3031:3031
    links:
      - mongodb
      - redis
    environment:
      - MONGO_HOST=mongodb
      - REDIS_HOST=redis
      #- NOTIFICATION_PORT=3031
    depends_on:
      - mongodb
      - redis
      - mail
    command: sh -c "npm run build && npm run debug"

  mail:
    image: schickling/mailcatcher
    ports:
      - 1080:1080