version: "3.7"

services:

  server:
    depends_on:
      - calendar
    environment:
      - CALENDAR_URI=http://calendar:3000
      - CALENDAR_API_KEY=test123

  client:
    environment:
      - CALENDAR_SERVICE_ENABLED=true

  ### Schul-Cloud Calendar
  ###
  calendar-postgres:
    image: postgres:${POSTGRES_DOCKER_TAG:-latest}
    depends_on:
      - calendar-init
    ports:
      - "5432:5432"
    volumes:
      - 'data-calendar-postgres:/var/lib/postgresql/data'
      - 'postgres-init:/docker-entrypoint-initdb.d'
    environment:
      - CALENDAR_API_KEY=test123
      - API_KEY=test123
      - POSTGRES_DB=schulcloud_calendar
      - POSTGRES_USER=node
      - POSTGRES_PASSWORD=genericpassword
    restart: unless-stopped
    #command: ls /docker-entrypoint-initdb.d


  calendar:
    image: schulcloud/schulcloud-calendar:${CALENDAR_DOCKER_TAG:-latest}
    build:
      context: ${CALENDAR_PATH:-.keep_empty}
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - calendar-postgres
    environment:
      # ENV
      - NODE_ENV=production
      # DB Credentials
      - DB_PASSWORD=genericpassword
      - DB_HOST=calendar-postgres
      - DB_USERNAME=node
      - DB_DATABASE=schulcloud_calendar
      # Paths
      - SCHULCLOUD_BASE_PATH=http://server:3030
      - NOTIFICATION_SERVICE_BASE_PATH=http://notification-service:3040
      - NOTIFICATION_SERVICE_NEW_NOTIFICATION=http://notification-service:3040/messages
    restart: unless-stopped
    command: npm start

  calendar-init:
    image: schulcloud/schulcloud-calendar:${CALENDAR_DOCKER_TAG:-latest}
    build:
      context: ${CALENDAR_PATH:-.keep_empty}
      dockerfile: Dockerfile
    init: true
    volumes:
      - 'postgres-init:/docker-entrypoint-initdb.d'
    command: /bin/sh -c 'mv schema.sql /docker-entrypoint-initdb.d/01-schema.sql && mv example_data.sql /docker-entrypoint-initdb.d/02-data.sql'

volumes:
  data-calendar-postgres:
  postgres-init: