version: "3.2"

services:

###########
### need more configuration to use it
###########
### Libre Office
  ###
  libreoffice:
    image: schulcloud/libreoffice:latest
    ports:
      - "9980:9980"
    volumes:
      - ./loolwsd.xml:/etc/loolwsd/loolwsd.xml
    environment:
      domain: localhost:9980
      server_name: server:3030
      extra_params: --o:ssl.enable=false
    restart: unless-stopped