version: "3.2"

services:

  client:
    links:
      - edtr
      - edtr-server
    environment:
      - EDITOR_URL=http://edtr-server:4001
      - EDTR_SOURCE=http://edtr:1234

  #### Editor
  ###
  edtr:
    build:
      context: ../../edtrio
      dockerfile: Dockerfile.develop
    container_name: edtr
    volumes:
      - ../../edtrio:/home/node/app
    environment:
     - EDITOR_API_URL=http://edtr-server:4001
     - SERVER_API_URL=http://server:3030
     - EDITOR_SOCKET_URL=ws://edtr-server:4001
    ports:
      - 1234:1234
      - 1235:1235 #refresh port for the browser
    restart: unless-stopped
    command: npm run dev:edtr


  edtr-server:
    build:
      context: ../../schulcloud-editor
      dockerfile: Dockerfile.develop
    container_name: edtr-server
    depends_on:
      - mongodb
    volumes:
      - ../../schulcloud-editor:/usr/src/app
    environment:
      - DB_URL=mongodb://mongodb:27017/edtr
    ports:
      - 4001:4001
      - 4002:4002 #debug
    restart: unless-stopped

